# -*- coding: utf-8 -*-
"""gender_gap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NsR_15Sxlaf5CxldEfLw7BMeEoHCm2R
"""

#importing libraries
import pandas as pd
import matplotlib.pyplot as plt

#loading dataset for female labor force participation
df = pd.read_csv("data.csv", skiprows=4)
df.head()

df.shape

# selecting India specifically
india = df[df["Country Code"] == "IND"].copy()
india

# selecting years 1990-2026
years = [str(year) for year in range(1990, 2026)]

india = india[["Country Name", "Country Code", "Indicator Name", "Indicator Code"] + years]
# changing format from wide to long
india_long = india.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Female_LFPR"
)
india_long["Year"] = india_long["Year"].astype(int)

india_long["Female_LFPR"] = pd.to_numeric(
    india_long["Female_LFPR"],
    errors="coerce"
)

india_long.head()

"""The dataset contains annual observations of female labour force participation in India from 1990 onwards. The female LFPR was around 30.3% in 1990 and increased gradually during the 1990s"""

#checking for missing data
india_long.isnull().sum()

india_long.info()

# final female data
female = india_long[
    ["Year", "Female_LFPR"]
].copy()
female = female.sort_values("Year").reset_index(drop=True)
female.head(10)

#calculate change in female participation
female["Annual_Change"] = female["Female_LFPR"].diff()
female["Percentage_Change"] = (
    female["Female_LFPR"].pct_change() * 100
)

female.head()

#plotting female Labour force participation
plt.figure(figsize=(12, 6))

plt.plot(
    female["Year"],
    female["Female_LFPR"],
    marker="o"
)

plt.title("Female Labour Force Participation Rate in India (1990–2025)")
plt.xlabel("Year")
plt.ylabel("Labour Force Participation Rate (%)")
plt.grid(alpha=0.3)

plt.show()

"""Female labour force participation increased from the early 1990s and reached its highest level in 2005 at 34.85%. It subsequently declined substantially, reaching 25.998% in 2020, before recovering to approximately 32.4% by 2025."""

#loading the dataset for male labor force participation
male = pd.read_csv("data_m.csv")
male.head()

male.shape

# selecting for india only
male_india = male[male["Country Code"] == "IND"].copy()
male_india.head()

#selecting for the years 1990-2025
years = [str(year) for year in range(1990, 2026)]

male_india = male_india[["Country Name", "Country Code", "Series Name", "Series Code"] + years]
# changing format from wide to long
male_long = male_india.melt(
    id_vars=[
        "Country Name",
        "Country Code",
        "Series Name",
        "Series Code"
    ],
    var_name="Year",
    value_name="Male_LFPR"
)
male_long.head()

male_long["Year"] = male_long["Year"].astype(int)

male_long["Male_LFPR"] = pd.to_numeric(
    male_long["Male_LFPR"],
    errors="coerce"
)

#checking for missing data
male_long.isnull().sum()

male_long.info()

# final male lfpr data
male_clean = male_long[
    ["Year", "Male_LFPR"]
].copy()
male_clean = male_clean.sort_values("Year").reset_index(drop=True)
male_clean.head(10)

# joining female and male lfpr data
df_final = pd.merge(
    female,
    male_clean,
    on="Year",
    how="inner"
)

# calculating the gender gap
df_final["Gender_Gap"] = (
    df_final["Male_LFPR"] -
    df_final["Female_LFPR"]
)

# calculating the female - male ratio
df_final["Female_Male_Ratio"] = (
    df_final["Female_LFPR"] /
    df_final["Male_LFPR"]
)

df_final["Female_Male_Ratio_Pct"] = (
    df_final["Female_Male_Ratio"] * 100
)

df_final.head()

df_final.info()

df_final.isnull().sum()

# plotting the lfpr for males and females in India
plt.figure(figsize=(12, 6))

plt.plot(
    df_final["Year"],
    df_final["Female_LFPR"],
    marker="o",
    label="Female"
)

plt.plot(
    df_final["Year"],
    df_final["Male_LFPR"],
    marker="o",
    label="Male"
)

plt.title(
    "Labour Force Participation Rate in India: Male vs Female"
)

plt.xlabel("Year")
plt.ylabel("Labour Force Participation Rate (%)")

plt.legend()
plt.grid(alpha=0.3)

plt.savefig(
    "male_vs_female_lfpr.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Male labour force participation remained considerably higher than female participation throughout 1990–2025. While both series declined over parts of the period, the gap between male and female participation remained substantial."""

# plotting the gender gap
plt.figure(figsize=(12, 6))

plt.plot(
    df_final["Year"],
    df_final["Gender_Gap"],
    marker="o"
)

plt.title(
    "Gender Gap in Labour Force Participation in India"
)

plt.xlabel("Year")
plt.ylabel("Gender Gap (percentage points)")

plt.grid(alpha=0.3)

plt.savefig(
    "gender_gap_india.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""The gender gap declined from approximately 53.75 percentage points in 1990 to 45.20 percentage points in 2025. The gap narrowed particularly toward the later part of the period, although a sizeable difference between male and female participation remained."""

# calculate average based on decades
def period(year):
    if 1990 <= year <= 1999:
        return "1990–1999"
    elif 2000 <= year <= 2009:
        return "2000–2009"
    elif 2010 <= year <= 2019:
        return "2010–2019"
    else:
        return "2020–2025"

df_final["Period"] = df_final["Year"].apply(period)

period_summary = df_final.groupby("Period").agg(
    Average_Female_LFPR=("Female_LFPR", "mean"),
    Average_Male_LFPR=("Male_LFPR", "mean"),
    Average_Gender_Gap=("Gender_Gap", "mean")
).reset_index()
period_summary

"""The average female LFPR was highest during 2000–2009 at 33.39% and lowest during 2010–2019 at 26.89%. The average gender gap was largest during 1990–1999 and lowest during 2020–2025, indicating a reduction in the average participation difference over these periods"""

# plotting the average female lfpr by decades
plt.figure(figsize=(10, 6))

plt.bar(
    period_summary["Period"],
    period_summary["Average_Female_LFPR"]
)

plt.title(
    "Average Female Labour Force Participation Rate by Period"
)

plt.xlabel("Period")
plt.ylabel("Average LFPR (%)")

plt.xticks(rotation=20)

plt.savefig(
    "female_lfpr_by_period.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Female labour force participation increased on average from 31.52% in 1990–1999 to 33.39% in 2000–2009. It then declined to 26.89% during 2010–2019 before recovering to 29.82% during 2020–2025."""

plt.figure(figsize=(10, 6))

plt.bar(
    period_summary["Period"],
    period_summary["Average_Gender_Gap"]
)

plt.title(
    "Average Gender Gap in Labour Force Participation"
)

plt.xlabel("Period")
plt.ylabel("Gender Gap (percentage points)")

plt.xticks(rotation=20)

plt.savefig(
    "gender_gap_by_period.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Female labour force participation increased on average from 31.52% in 1990–1999 to 33.39% in 2000–2009. It then declined to 26.89% during 2010–2019 before recovering to 29.82% during 2020–2025."""

female_change = (
    df_final.iloc[-1]["Female_LFPR"] -
    df_final.iloc[0]["Female_LFPR"]
)

print(
    f"Change in female LFPR from {df_final.iloc[0]['Year']} "
    f"to {df_final.iloc[-1]['Year']}: "
    f"{female_change:.2f} percentage points"
)

gap_change = (
    df_final.iloc[-1]["Gender_Gap"] -
    df_final.iloc[0]["Gender_Gap"]
)

print(
    f"Change in gender gap: {gap_change:.2f} percentage points"
)

#lowest female LFPR
lowest = df_final.loc[
    df_final["Female_LFPR"].idxmin()
]

print(lowest)

#Highest Female LFPR
highest = df_final.loc[
    df_final["Female_LFPR"].idxmax()
]

print(highest)

#largest annual increase
df_final.loc[df_final["Female_LFPR"].diff().idxmax()]

#largest annual decline
largest_decline = df_final.loc[
    df_final["Female_LFPR"].diff().idxmin()
]

largest_decline

"""- LFPR increased by approximately 2.17 percentage points between 1990 and 2025. However, this net change masks substantial fluctuations during the intervening period, including a decline after the mid-2000s and a subsequent recovery.

- The lowest female LFPR in the dataset occurred in 2020 at 25.998%. In the following year, participation increased to 27.724%, representing an annual increase of approximately 1.73 percentage points.

- The lowest female LFPR in the dataset occurred in 2020 at 25.998%. In the following year, participation increased to 27.724%, representing an annual increase of approximately 1.73 percentage points.
"""

# comparing South Asian Countries
countries = ["India", "Bangladesh", "Sri Lanka", "Nepal", "Pakistan"]

df_countries = df[df["Country Name"].isin(countries)].copy()

df_countries[["Country Name", "Country Code"]]

year_columns = [
    col for col in df_countries.columns
    if any(str(year) in str(col) for year in range(1990, 2026))
]

print(year_columns)

df_countries = df_countries[
    ["Country Name", "Country Code", "Indicator Name", "Indicator Code"]
    + year_columns
]

df_long = df_countries.melt(
    id_vars=[
        "Country Name",
        "Country Code",
        "Indicator Name",
        "Indicator Code"
    ],
    var_name="Year",
    value_name="Female_LFPR"
)

df_long["Year"] = (
    df_long["Year"]
    .str.extract(r"(\d{4})")[0]
    .astype(int)
)
df_long["Female_LFPR"] = pd.to_numeric(
    df_long["Female_LFPR"],
    errors="coerce"
)

df_clean = df_long[
    ["Country Name", "Year", "Female_LFPR"]
].copy()

df_clean = df_clean.sort_values(
    ["Country Name", "Year"]
).reset_index(drop=True)
df_clean.head()

plt.figure(figsize=(12, 6))

for country in countries:
    country_data = df_clean[
        df_clean["Country Name"] == country
    ]

    plt.plot(
        country_data["Year"],
        country_data["Female_LFPR"],
        marker="o",
        markersize=3,
        label=country
    )

plt.title(
    "Female Labour Force Participation in South Asia (1990–2025)"
)

plt.xlabel("Year")
plt.ylabel("Female Labour Force Participation Rate (%)")

plt.legend()
plt.grid(alpha=0.3)

plt.savefig(
    "female_lfpr_south_asia.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""Female labour force participation follows noticeably different trajectories across the five South Asian countries. Sri Lanka starts from a relatively high level but declines over the period, while Bangladesh and Pakistan show substantial increases between 1990 and 2025."""

start = df_clean[
    df_clean["Year"] == 1990
][["Country Name", "Female_LFPR"]].rename(
    columns={"Female_LFPR": "LFPR_1990"}
)

end = df_clean[
    df_clean["Year"] == 2025
][["Country Name", "Female_LFPR"]].rename(
    columns={"Female_LFPR": "LFPR_2025"}
)

change = pd.merge(
    start,
    end,
    on="Country Name"
)

change["Change"] = (
    change["LFPR_2025"] -
    change["LFPR_1990"]
)

change

"""Between 1990 and 2025, Bangladesh recorded an increase of 14.44 percentage points, while Pakistan increased by 12.85 points and Nepal by 6.84 points. India experienced a smaller net increase of 2.17 points, whereas Sri Lanka recorded a decline of 14.16 percentage points"""

plt.figure(figsize=(10, 6))

plt.bar(
    change["Country Name"],
    change["Change"]
)

plt.axhline(0, linewidth=1)

plt.title(
    "Change in Female Labour Force Participation: 1990–2025"
)

plt.xlabel("Country")
plt.ylabel("Change (percentage points)")

plt.xticks(rotation=20)

plt.savefig(
    "lfpr_change_1990_2025.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""The chart highlights substantial differences in the change in female labour force participation across South Asian countries. Bangladesh and Pakistan show large positive changes over the period, while Sri Lanka shows a negative change; India's change is comparatively smaller"""

df_clean["Period"] = df_clean["Year"].apply(period)

period_summary = (
    df_clean
    .groupby(["Country Name", "Period"])["Female_LFPR"]
    .mean()
    .reset_index()
)

period_summary

